name: scalar

dependencies:
  - name: OpenZeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.2

solidity:
  import_remapping:
    - "@openzeppelin/contracts=OpenZeppelin/4.8.2"

ethereum:
  default_network: local
  local:
    default_provider: hardhat

hardhat:
  request_timeout: 20 # Defaults to 30
  fork_request_timeout: 600 # Defaults to 300
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

test:
  mnemonic: test test test test test test test test test test test junk
  number_of_accounts: 5
